describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000')
    cy.get('#root img[alt="Аудио"]').click();
    cy.get('#root img[alt="AirPods 2"]').click();
    cy.get('#root button.add-to-cart-button').click();
    cy.get('#root a[href="/category/%D0%90%D1%83%D0%B4%D0%B8%D0%BE"]').click();
    cy.get('#root a[href="/catalog"]').click();
    cy.get('#root img[alt="Смартфоны"]').click();
    cy.get('#root img[alt="IPhone 14"]').click();
    cy.get('#root button.add-to-cart-button').click();
    cy.get('#root a[href="/category/%D0%A1%D0%BC%D0%B0%D1%80%D1%82%D1%84%D0%BE%D0%BD%D1%8B"]').click();
    cy.get('#root a[href="/catalog"]').click();
    cy.get('#root a[href="http://localhost:3000/category/Ноутбуки"]').click();
    cy.get('#root img[alt="MacBook Pro M4"]').click();
    cy.get('#root button.add-to-cart-button').click();
    cy.get('#root a.logo h1').click();
    cy.get('#root img[alt="Корзина"]').click();
    cy.get('#root div:nth-child(1) > div.cart-item-info > div.quantity-controls > button:nth-child(3)').click();
    cy.get('#root div:nth-child(1) > div.cart-item-info > div.quantity-controls > button:nth-child(1)').click();
    cy.get('#root div:nth-child(2) > div.cart-item-info > button.remove-btn').click();
    cy.get('#root button.clear-cart-button').click();
    cy.get('#root button.cart-close-btn').click();
    cy.get('#root img[alt="Ноутбуки"]').click();
    cy.get('#root img[alt="MacBook Pro M4"]').click();
    cy.get('#root button.add-to-cart-button').click();
    cy.get('#root img[alt="Корзина"]').click();
    cy.get('#root a.checkout-cart-button').click();
    cy.get('#root [name="customerFullName"]').click();
    cy.get('#root [name="customerFullName"]').type('Иванов Иван Иванович');
    cy.get('#root [name="customerEmail"]').click();
    cy.get('#root [name="customerEmail"]').type('email@example.com');
    cy.get('#root [name="customerPhoneNumber"]').click();
    cy.get('#root [name="customerPhoneNumber"]').type('89999999999');
    cy.get('#root [name="payMethod"]').select('Наличными');
    cy.get('#root [name="payMethod"]').select('Онлайн');
    cy.get('#root [name="shipMethod"]').select('Служба доставки');
    cy.get('#root [name="shipCompanyId"]').select('2');
    cy.get('#root [name="shipAddress"]').click();
    cy.get('#root [name="shipMethod"]').select('Самовывоз');
    cy.get('#root [name="customerPhoneNumber"]').click();
    cy.get('#root [name="customerPhoneNumber"]').clear();
    cy.get('#root [name="customerPhoneNumber"]').type('8999999999');
    cy.get('#root button.submit-button').click();
    cy.get('#root [name="customerPhoneNumber"]').click();
    cy.get('#root [name="customerPhoneNumber"]').clear();
    cy.get('#root [name="customerPhoneNumber"]').type('89999999');
    cy.get('#root button.submit-button').click();
    cy.get('#root [name="customerPhoneNumber"]').clear();
    cy.get('#root button.submit-button').click();
    cy.get('#root [name="customerPhoneNumber"]').click();
    cy.get('#root [name="customerPhoneNumber"]').type('89999999999');
    cy.get('#root [name="customerEmail"]').click();
    cy.get('#root [name="customerPhoneNumber"]').click();
    cy.get('#root [name="customerEmail"]').click();
    cy.get('#root [name="customerEmail"]').clear();
    cy.get('#root [name="customerEmail"]').type('email@example');
    cy.get('#root button.submit-button').click();
    cy.get('#root [name="customerEmail"]').type('.');
    cy.get('#root button.submit-button').click();
    cy.get('#root [name="customerEmail"]').type('com');
    cy.get('#root button.submit-button').click();
    cy.get('#root [name="customerFullName"]').click();
    cy.get('#root [name="customerFullName"]').clear();
    cy.get('#root [name="customerFullName"]').type('Иванов Иван ');
    cy.get('#root button.submit-button').click();
    cy.get('#root [name="customerFullName"]').type('Иванович');
    cy.get('#root button.submit-button').click();
    cy.get('#root button:nth-child(3)').click();
    cy.get('#root button:nth-child(1)').click();
    cy.get('#root a.logo h1').click();
    cy.get('#root img[alt="Корзина"]').click();
    cy.get('#root button.clear-cart-button').click();
    cy.get('#root button.cart-close-btn').click();
  })
})